### ISSUE TITLE
Unable to add new WSDL - HIS Metadata Fetcher

### ISSUE THREAD

**Issue by xhqiao89** [xhqiao89/HydroDesktop_test#14]
<b>jseppi[CodePlex]</b> <br />An IndexOutOfRangeException is thrown when attempting to Add New WSDL using the HIS Metadata Fetcher. The exception text is shown below. A screenshot is also attached.

************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at HIS_Database.Classes.Functions.saveWSDL(String wsdlURL) in C:\dev\hydrodesktop\Source\Plugins\DataFetcher\Classes\Functions.cs:line 956
at HIS_Database.Forms.AddWSDLForm.btnAddWSDL_Click(Object sender, EventArgs e) in C:\dev\hydrodesktop\Source\Plugins\DataFetcher\Forms\AddWSDLForm.cs:line 139
at System.Windows.Forms.Control.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnClick(EventArgs e)
at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
at System.Windows.Forms.Control.WmMouseUp(Messageamp m, MouseButtons button, Int32 clicks)
at System.Windows.Forms.Control.WndProc(Messageamp m)
at System.Windows.Forms.ButtonBase.WndProc(Messageamp m)
at System.Windows.Forms.Button.WndProc(Messageamp m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Messageamp m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Messageamp m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
HydroDesktop
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/HydroDesktop.exe
System.Windows.Forms
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
System.Drawing
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
MapWindow
Assembly Version: 6.0.0.0
Win32 Version: 6.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/MapWindow.DLL
System.Configuration
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
System.Xml
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
System.Core
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.1 built by: SP
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
AdvancedSearch
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/Plugins/AdvancedSearch/AdvancedSearch.dll
HydroDesktop.Database
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/HydroDesktop.Database.DLL
System.Data
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
HIS_Database
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/Plugins/DataFetcher/HIS_Database.dll
HydroModeler
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/Plugins/HydroModeler/HydroModeler.dll
SamplePlugin
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/Plugins/SamplePlugin/SamplePlugin.dll
GeoShapeEditor
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/Plugins/ShapeEditor/GeoShapeEditor.dll
System.Data.SQLite
Assembly Version: 1.0.60.0
Win32 Version: 1.0.60.0
CodeBase: file:///C:/Users/JamTay/Desktop/hydro/Binaries/System.Data.SQLite.DLL
System.Data.Entity
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.1 built by: SP
CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Data.Entity/3.5.0.0__b77a5c561934e089/System.Data.Entity.dll
System.Transactions
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_32/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
System.EnterpriseServices
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.4016 (NetFxQFE.050727-4000)
CodeBase: file:///C:/Windows/assembly/GAC_32/System.EnterpriseServices/2.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

ltconfigurationgt
ltsystem.windows.forms jitDebugging=quottruequot /gt
lt/configurationgt

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by xhqiao89** [comment]
<b>jseppi[CodePlex]</b> <br />I think the issue is related to the SQLite DLL version when using a 64-bit OS (I am running Windows 7 64-bit). I just updated all from SVN, and then changed my local build configuration to target x86 instead of Any. After rebuilding, I can
 successfully add WSDLs, update the DB, etc.
