### ISSUE TITLE
Search and Download by HUC and map crashes

### ISSUE THREAD

**Issue by xhqiao89** [xhqiao89/HydroDesktop_test#22]
<b>rhooper[CodePlex]</b> <br />Using search and download appears not to work for HUCs. I tried Charles River for a variety of date ranges for discharge and DO and didn't get any returns. When I searched for same data series in Massachusetts, I got returns in the Charles Basin (I think).
 I'm not sure because when I tried to expand the map, the program crashed:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
at AdvancedSearch.Classes.MapNavControl.ZoomInOneStep() in D:\dev\HydroDesktop\Source\Plugins\AdvancedSearch\Classes\MapNavControl.cs:line 122
at AdvancedSearch.Classes.MapNavControl.tmrZoomTool_Tick(Object sender, EventArgs e) in D:\dev\HydroDesktop\Source\Plugins\AdvancedSearch\Classes\MapNavControl.cs:line 100
at System.Windows.Forms.Timer.OnTick(EventArgs e)
at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Messageamp m)
at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
CodeBase: file:///c:/WINDOWS/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
HydroDesktop
Assembly Version: 0.1.0.31288
Win32 Version: 0.1.0.31288
CodeBase: file:///C:/Program%20Files/HydroDesktop/HydroDesktop.exe
System.Windows.Forms
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
System.Drawing
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
MapWindow
Assembly Version: 6.0.0.0
Win32 Version: 6.0.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/MapWindow.DLL
System.Core
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.1 built by: SP
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
System.Xml
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3082 (QFE.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
HydroModeler
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/HydroModeler.dll
Oatc.OpenMI.Gui.Core
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/Oatc.OpenMI.Gui.Core.DLL
Oatc.OpenMI.Sdk.Backbone
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/Oatc.OpenMI.Sdk.Backbone.DLL
OpenMI.Standard
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/OpenMI.Standard.DLL
Oatc.OpenMI.Gui.Controls
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/Oatc.OpenMI.Gui.Controls.DLL
System.Configuration
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
Oatc.OpenMI.Sdk.Buffer
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/Oatc.OpenMI.Sdk.Buffer.dll
Oatc.OpenMI.Sdk.DevelopmentSupport
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/Oatc.OpenMI.Sdk.DevelopmentSupport.dll
Oatc.OpenMI.Sdk.Spatial
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/Oatc.OpenMI.Sdk.Spatial.dll
Oatc.OpenMI.Sdk.Wrapper
Assembly Version: 1.4.0.0
Win32 Version: 1.4.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/HydroModeler/Oatc.OpenMI.Sdk.Wrapper.dll
HIS_Database
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/MetadataFetcher/HIS_Database.dll
HydroDesktop.Database
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/HydroDesktop.Database.DLL
Search
Assembly Version: 0.1.0.23926
Win32 Version: 0.1.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Plugins/Search/Search.dll
System.Data
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll
System.Web.Services
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Web.Services/2.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
System.Design
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Design/2.0.0.0__b03f5f7f11d50a3a/System.Design.dll
czuup3nr
Assembly Version: 0.0.0.0
Win32 Version: 0.0.0.0
CodeBase: file:///C:/Documents%20and%20Settings/rhooper.CUAHSI_RHOOPER/Local%20Settings/Temp/czuup3nr.dll
t1p4wl6r
Assembly Version: 0.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
System.Data.SQLite
Assembly Version: 1.0.60.0
Win32 Version: 1.0.60.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/System.Data.SQLite.DLL
System.Data.Entity
Assembly Version: 3.5.0.0
Win32 Version: 3.5.30729.1 built by: SP
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Data.Entity/3.5.0.0__b77a5c561934e089/System.Data.Entity.dll
System.Transactions
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll
Vici.CoolStorage
Assembly Version: 1.2.1.1059
Win32 Version: 1.2.1.1059
CodeBase: file:///C:/Program%20Files/HydroDesktop/Vici.CoolStorage.DLL
System.EnterpriseServices
Assembly Version: 2.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_32/System.EnterpriseServices/2.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
Vici.CoolStorage.SQLite
Assembly Version: 1.0.0.0
Win32 Version: 1.0.0.0
CodeBase: file:///C:/Program%20Files/HydroDesktop/Vici.CoolStorage.SQLite.DLL
a5i1nciv
Assembly Version: 0.0.0.0
Win32 Version: 0.0.0.0
CodeBase: file:///C:/Documents%20and%20Settings/rhooper.CUAHSI_RHOOPER/Local%20Settings/Temp/a5i1nciv.dll
yb1ij9ug
Assembly Version: 0.0.0.0
Win32 Version: 2.0.50727.3053 (netfxsp.050727-3000)
CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

ltconfigurationgt
ltsystem.windows.forms jitDebugging=quottruequot /gt
lt/configurationgt

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by xhqiao89** [comment]
<b>jirikadlec2[CodePlex]</b> <br />Not getting any results for the keyword 'Discharge' is related to issues with synonyms on the HIS Central web service. The list of available keywords is populated using the GetSearchableConcepts query which returns all keywords including synonyms. However,
 if the keyword is not a basic keyword ('Streamflow') but a synonym ('Discharge'), GetSeriesCatalogForBox returns an empty result set. The HIS Central team at SDSC is working on this issue.

As a temporary workaround we may try to exclude synonyms from the displayed list of keywords.
